#PBS -N cyltest
#PBS -o yourfilepath/$PBS_JOBID.out
#PBS -e yourfilepath/$PBS_JOBID.err
#PBS -l nodes=1:gpus=1:S
#PBS -r y

cd $PBS_O_WORKDIR
echo Time is `date`
echo Directory is $PWD
echo this job runs on following nodes:
echo -n "Node:"
cat $PBS_NODEFILE
echo -n "Gpus:"
cat $PBS_GPUFILE
echo "CUDA_VISIBLE_DEVICES:"$CUDA_VISIBLE_DEVICES

startdocker -P yourfilepath -c "/usr/bin/python yourfilepath/main.py" etcis:5000/isfishingsnow/ustcai:v2.0
